// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyVTzGUAkNMdZ9QbKD4UUSWL7ek0p3bes',
    appId: '1:120282023865:web:4784dfad779adda513d868',
    messagingSenderId: '120282023865',
    projectId: 'whatsappclone-1ef86',
    authDomain: 'whatsappclone-1ef86.firebaseapp.com',
    storageBucket: 'whatsappclone-1ef86.firebasestorage.app',
    measurementId: 'G-5MN5G4L4P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8oc-ftYQBezQHnnAl_ET2bAEA3ZAtUT4',
    appId: '1:120282023865:android:d9b4c4f3befa40e213d868',
    messagingSenderId: '120282023865',
    projectId: 'whatsappclone-1ef86',
    storageBucket: 'whatsappclone-1ef86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJj1NuNrbh2I7yh6Z7bjuU2dd2Tvj5kvA',
    appId: '1:120282023865:ios:d4f76dab2c20682913d868',
    messagingSenderId: '120282023865',
    projectId: 'whatsappclone-1ef86',
    storageBucket: 'whatsappclone-1ef86.firebasestorage.app',
    iosBundleId: 'com.example.waclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJj1NuNrbh2I7yh6Z7bjuU2dd2Tvj5kvA',
    appId: '1:120282023865:ios:d4f76dab2c20682913d868',
    messagingSenderId: '120282023865',
    projectId: 'whatsappclone-1ef86',
    storageBucket: 'whatsappclone-1ef86.firebasestorage.app',
    iosBundleId: 'com.example.waclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyVTzGUAkNMdZ9QbKD4UUSWL7ek0p3bes',
    appId: '1:120282023865:web:51e44d42aff93eaf13d868',
    messagingSenderId: '120282023865',
    projectId: 'whatsappclone-1ef86',
    authDomain: 'whatsappclone-1ef86.firebaseapp.com',
    storageBucket: 'whatsappclone-1ef86.firebasestorage.app',
    measurementId: 'G-9690HKVGEP',
  );
}
